name: NPM Publish
on:
  push:
    tags:
      - '*.*.*'

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish-jsr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Publish package
        run: npx jsr publish

  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Convert to NPM package
        run: deno run -A scripts/build_npm.ts ${{ github.ref_name }}
      - name: Publish to NPM
        run: npm publish --provenance --access public